export const ErrorCodes = {
    USER_NOT_FOUND: "USER_NOT_FOUND",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
    INVALID_ROLE: "INVALID_ROLE",
    ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
    NOT_FOUND: "NOT_FOUND",
} as const;

export type ErrorCode =
    (typeof ErrorCodes)[keyof typeof ErrorCodes];