"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _admin_access_control from './admin-access-control.bones.json'
import _admin_dashboard from './admin-dashboard.bones.json'

configureBoneyard({"animate":"shimmer","speed":"2s"})

registerBones({
  "admin-access-control": _admin_access_control,
  "admin-dashboard": _admin_dashboard,
})
