"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const authenticate_middleware_1 = require("../../middleware/authenticate.middleware");
const auth_controller_1 = require("./auth.controller");
const router = (0, express_1.Router)();
router.post("/login", auth_controller_1.loginController);
router.post("/signup", auth_controller_1.createUserController);
router.get("/roles", auth_controller_1.getRoleController);
router.get("/permissions", auth_controller_1.getPermissionController);
router.get("/users", auth_controller_1.getUsersController);
router.put("/roles/:id/permissions", auth_controller_1.updateRolePermissionsController);
router.put("/users/:id", auth_controller_1.updateUserController);
router.get("/me", authenticate_middleware_1.authenticate, auth_controller_1.me);
router.post("/logout", authenticate_middleware_1.authenticate, auth_controller_1.logout);
exports.default = router;
